-- Add suggested_listening_content column to store cleaned/structured HTML
ALTER TABLE public.module_lessons
ADD COLUMN IF NOT EXISTS suggested_listening_content TEXT;

-- Add comment for documentation
COMMENT ON COLUMN public.module_lessons.suggested_listening_content IS 'Cleaned and structured HTML content for suggested listening lessons. Generated by the process-suggested-listening edge function.';